version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mercadolibre_clone_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/code      # Montás el proyecto raíz en /code
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/code
